version: '2'
services:
  firefox:
    image: selenium/node-chrome
    volumes:
    - /dev/shm:/dev/shm
    depends_on:
    - hub
    environment:
      HUB_HOST: hub

#  chrome:
#    image: selenium/node-chrome:3.14.0-arsenic
#    volumes:
#    - /dev/shm:/dev/shm
#    depends_on:
#    - hub
#    environment:
#      HUB_HOST: hub

  hub:
    image: selenium/hub
    ports:
    - "4446:4444"